package app

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"strings"
	"time"

	appconfig "promptd/internal/config"

	"go.uber.org/zap"
)

func PrepareTLSConfig(cfg *appconfig.Config, logger *zap.Logger) (*tls.Config, string, string, error) {
	if !cfg.Server.TLS.Enabled {
		return nil, "", "", nil
	}

	certFile := strings.TrimSpace(cfg.Server.TLS.CertFile)
	keyFile := strings.TrimSpace(cfg.Server.TLS.KeyFile)
	if certFile == "" || keyFile == "" {
		return nil, "", "", fmt.Errorf("server.tls.cert_file and server.tls.key_file are required when TLS is enabled")
	}

	if cfg.Server.TLS.AutoGenerate {
		if err := ensureSelfSignedCertificate(certFile, keyFile, cfg.Server.Address, cfg.Server.TLS.Hosts, logger); err != nil {
			return nil, "", "", err
		}
	}

	cert, err := tls.LoadX509KeyPair(certFile, keyFile)
	if err != nil {
		return nil, "", "", fmt.Errorf("load TLS certificate: %w", err)
	}

	return &tls.Config{
		Certificates: []tls.Certificate{cert},
		MinVersion:   tls.VersionTLS12,
	}, certFile, keyFile, nil
}

func ensureSelfSignedCertificate(certFile, keyFile, address string, hosts []string, logger *zap.Logger) error {
	certExists := fileExists(certFile)
	keyExists := fileExists(keyFile)
	if certExists && keyExists {
		logger.Info("using existing autogenerated TLS certificate", zap.String("cert_file", certFile), zap.String("key_file", keyFile))
		return nil
	}
	if certExists != keyExists {
		return fmt.Errorf("autogenerated TLS certificate files are inconsistent; ensure both files exist or delete both: %s, %s", certFile, keyFile)
	}

	resolvedHosts := normalizeTLSHosts(hosts, address)
	if len(resolvedHosts) == 0 {
		return fmt.Errorf("no valid TLS hosts available for certificate generation")
	}
	if err := os.MkdirAll(filepath.Dir(certFile), 0o755); err != nil {
		return fmt.Errorf("create TLS cert directory: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(keyFile), 0o755); err != nil {
		return fmt.Errorf("create TLS key directory: %w", err)
	}

	certPEM, keyPEM, err := generateSelfSignedPEM(resolvedHosts)
	if err != nil {
		return err
	}
	if err := os.WriteFile(certFile, certPEM, 0o644); err != nil {
		return fmt.Errorf("write TLS cert file: %w", err)
	}
	if err := os.WriteFile(keyFile, keyPEM, 0o600); err != nil {
		return fmt.Errorf("write TLS key file: %w", err)
	}
	logger.Info("generated self-signed TLS certificate",
		zap.String("cert_file", certFile),
		zap.String("key_file", keyFile),
		zap.Strings("hosts", resolvedHosts),
	)
	return nil
}

func generateSelfSignedPEM(hosts []string) ([]byte, []byte, error) {
	privateKey, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return nil, nil, fmt.Errorf("generate TLS private key: %w", err)
	}

	serialNumber, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return nil, nil, fmt.Errorf("generate TLS serial number: %w", err)
	}

	tmpl := &x509.Certificate{
		SerialNumber: serialNumber,
		Subject: pkix.Name{
			CommonName:   hosts[0],
			Organization: []string{"promptd"},
		},
		NotBefore:             time.Now().Add(-time.Hour),
		NotAfter:              time.Now().Add(365 * 24 * time.Hour),
		KeyUsage:              x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		BasicConstraintsValid: true,
	}
	for _, host := range hosts {
		if ip := net.ParseIP(host); ip != nil {
			tmpl.IPAddresses = append(tmpl.IPAddresses, ip)
			continue
		}
		tmpl.DNSNames = append(tmpl.DNSNames, host)
	}

	derBytes, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &privateKey.PublicKey, privateKey)
	if err != nil {
		return nil, nil, fmt.Errorf("create self-signed TLS certificate: %w", err)
	}

	certPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: derBytes})
	keyPEM := pem.EncodeToMemory(&pem.Block{Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(privateKey)})
	return certPEM, keyPEM, nil
}

func normalizeTLSHosts(configured []string, address string) []string {
	result := make([]string, 0, len(configured)+3)
	seen := map[string]bool{}
	addHost := func(host string) {
		host = strings.TrimSpace(host)
		if host == "" || seen[host] {
			return
		}
		seen[host] = true
		result = append(result, host)
	}

	for _, host := range configured {
		addHost(host)
	}

	addressHost := strings.TrimSpace(address)
	if h, _, err := net.SplitHostPort(addressHost); err == nil {
		addressHost = h
	}
	switch addressHost {
	case "", "0.0.0.0", "::", "[::]":
		addHost("localhost")
		addHost("127.0.0.1")
		addHost("::1")
	default:
		addHost(addressHost)
		if addressHost == "localhost" {
			addHost("127.0.0.1")
			addHost("::1")
		}
	}

	return result
}

func fileExists(path string) bool {
	if strings.TrimSpace(path) == "" {
		return false
	}
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}
